#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_chess_obs.py — 观察者视角彩色编号棋盘 (160宽×180高) + 直写打包 (2026-07-08 实测映射)。

映射 (lane 数字/色序探针实测, 用户视角):
  条: X 0..52=左条 lanes{6,7,8} / 53..105=中条 {3,4,5} / 106..159=右条 {0,1,2}(54宽)
  行: row r = 条内从"右边缘"数第 r 列 → r=(w-1)-p, 53宽条 r=53 落空
  竖: x=Y 直通 (0..179 上→下); 组内色序 R,G,B = lane_base+0/1/2
  fb bit: h=11-x//15, OUT=x%15, 32bit字=h//2, bit=(h%2)*16+OUT
输出: chess_obs_fb.tcl (mwr, 需外部 connect) + chess_obs_preview.png (4x)
"""
import os
from PIL import Image

W, H, CELL = 160, 180, 20          # 8 列 x 9 行 = 72 格
PAL = [(255,0,0),(0,255,0),(0,0,255),(255,255,0),(255,0,255),(0,255,255),(255,255,255)]
DARK_TEXT_BG = {(255,255,255),(255,255,0),(0,255,255)}
DIGITS = {
    '0':['111','101','101','101','111'], '1':['010','110','010','010','111'],
    '2':['111','001','111','100','111'], '3':['111','001','111','001','111'],
    '4':['101','101','111','001','001'], '5':['111','100','111','001','111'],
    '6':['111','100','111','101','111'], '7':['111','001','010','100','100'],
    '8':['111','101','111','101','111'], '9':['111','101','111','001','111'],
}
STRIPS = [(0, 53, 6), (53, 53, 3), (106, 54, 0)]   # (X起点, 宽, lane基)

def build_image():
    im = Image.new('RGB', (W, H), (0, 0, 0))
    px = im.load()
    gx, gy = W // CELL, H // CELL
    for cy in range(gy):
        for cx in range(gx):
            idx = cy * gx + cx
            bg = PAL[idx % 7]
            x0, y0 = cx * CELL, cy * CELL
            for dx in range(CELL):
                for dy in range(CELL):
                    px[x0+dx, y0+dy] = bg
            border = (0,0,0) if bg == (255,255,255) else (255,255,255)
            for d in range(CELL):
                px[x0+d, y0] = border; px[x0+d, y0+CELL-1] = border
                px[x0, y0+d] = border; px[x0+CELL-1, y0+d] = border
            fg = (0,0,0) if bg in DARK_TEXT_BG else (255,255,255)
            tx = x0 + 3
            for ch in str(idx):
                rows = DIGITS[ch]
                for ry, rows5 in enumerate(rows):
                    for rx, c in enumerate(rows5):
                        if c == '1':
                            for sx in range(2):
                                for sy in range(2):
                                    px[tx+rx*2+sx, y0+3+ry*2+sy] = fg
                tx += 8
    return im

def pack(im):
    px = im.load()
    # words[lane][row] = 6 个 32bit
    words = [[[0]*6 for _ in range(54)] for _ in range(9)]
    for X in range(W):
        for x0, w, base in STRIPS:
            if x0 <= X < x0 + w:
                p = X - x0
                r = (w - 1) - p
                if r > 53: continue
                for Y in range(H):
                    rgb = px[X, Y]
                    h = 11 - Y // 15
                    bit = (h % 2) * 16 + (Y % 15)
                    for ci in range(3):
                        if rgb[ci] >= 128:
                            words[base + ci][r][h // 2] |= 1 << bit
                break
    lines = ["# generated by gen_chess_obs.py — 观察者视角彩色编号棋盘 (实测映射)"]
    for lane in range(9):
        b = 0x40018000 + lane * 0x800
        for r in range(54):
            ws = ' '.join(f'0x{v:08X}' for v in words[lane][r])
            lines.append(f'mwr -force -size w 0x{b + r*0x20:08X} {{{ws}}} 6')
    return '\n'.join(lines) + '\n'

def main():
    d = os.path.dirname(os.path.abspath(__file__))
    im = build_image()
    im.resize((W*4, H*4), Image.NEAREST).save(os.path.join(d, 'chess_obs_preview.png'))
    with open(os.path.join(d, 'chess_obs_fb.tcl'), 'w') as f:
        f.write(pack(im))
    print("saved chess_obs_fb.tcl + preview")

if __name__ == '__main__':
    main()
