#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_lane_digits.py — lane 身份探针: lane i 的 fb 区写大数字 "i" (7 段码)。
一张照片同时解出: 区排列(数字值) / lane↔色(数字颜色) / 旋转+镜像(数字姿态)。

每 lane 条带 = 54(扫描,横) × 180(列,竖)。canvas (cx,cy): cx=row 0..53, cy=x 0..179。
像素映射 (与 fb_pack 同): h=11-x//15 (chip), OUT=x%15, 32bit字=h//2, bit=(h%2)*16+OUT。
数字下方加一短横条标记 canvas 底端 (辅助判上下)。
输出: tools/lane_digits_fb.tcl (mwr 行, 需外部 connect)。
"""
import os

SEGS = {  # 7 段: A顶 B右上 C右下 D底 E左下 F左上 G中
    0: "ABCDEF", 1: "BC", 2: "ABGED", 3: "ABGCD", 4: "FGBC",
    5: "AFGCD", 6: "AFGEDC", 7: "ABC", 8: "ABCDEFG",
}
W, H = 54, 180          # canvas: 宽=54 行(横), 高=180 列(竖)
BX, BY, BW, BH, S = 7, 30, 40, 90, 9   # 数字框 40x90, 笔画 9

def seg_rects(name):
    x0, y0, w, h = BX, BY, BW, BH
    m = y0 + h // 2
    return {
        'A': (x0, y0, x0 + w, y0 + S),
        'B': (x0 + w - S, y0, x0 + w, m + S // 2),
        'C': (x0 + w - S, m - S // 2, x0 + w, y0 + h),
        'D': (x0, y0 + h - S, x0 + w, y0 + h),
        'E': (x0, m - S // 2, x0 + S, y0 + h),
        'F': (x0, y0, x0 + S, m + S // 2),
        'G': (x0, m - S // 2, x0 + w, m + S // 2),
    }[name]

def render(digit):
    px = [[0] * H for _ in range(W)]   # px[cx][cy]
    for s in SEGS[digit]:
        x0, y0, x1, y1 = seg_rects(s)
        for cx in range(x0, x1):
            for cy in range(y0, y1):
                px[cx][cy] = 1
    for cx in range(12, 42):           # 底端标记条 (canvas 下方 y=150..160)
        for cy in range(150, 161):
            px[cx][cy] = 1
    return px

def main():
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lane_digits_fb.tcl")
    lines = ["# generated by gen_lane_digits.py — lane i = digit i + 底端标记条"]
    total = 0
    for lane in range(9):
        px = render(lane)
        base = 0x40018000 + lane * 0x800
        for row in range(54):
            words = [0] * 6
            for x in range(180):
                if px[row][x]:
                    h = 11 - x // 15
                    bit = (h % 2) * 16 + (x % 15)
                    words[h // 2] |= 1 << bit
            total += sum(bin(w).count('1') for w in words)
            ws = ' '.join(f'0x{w:08X}' for w in words)
            lines.append(f'mwr -force -size w 0x{base + row*0x20:08X} {{{ws}}} 6')
    with open(out, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"saved {out}, lit bits total={total}")

if __name__ == '__main__':
    main()
